Document: vulkan-extensionlayer
Title: Debian vulkan-extensionlayer Manual
Author: <insert document author here>
Abstract: This manual describes what vulkan-extensionlayer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vulkan-extensionlayer/vulkan-extensionlayer.sgml.gz

Format: postscript
Files: /usr/share/doc/vulkan-extensionlayer/vulkan-extensionlayer.ps.gz

Format: text
Files: /usr/share/doc/vulkan-extensionlayer/vulkan-extensionlayer.text.gz

Format: HTML
Index: /usr/share/doc/vulkan-extensionlayer/html/index.html
Files: /usr/share/doc/vulkan-extensionlayer/html/*.html
